# Generated by Django 3.1.4 on 2020-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auction_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_value',
            field=models.IntegerField(default=20000),
            preserve_default=False,
        ),
    ]
