# Generated by Django 3.1.4 on 2020-12-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201221_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='author',
        ),
    ]
