# Generated by Django 3.1.4 on 2020-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_bid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_value',
            field=models.IntegerField(blank=True),
        ),
    ]
