# Generated by Django 3.1.4 on 2020-12-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201222_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('SDN', 'SEDAN'), ('COP', 'COUPE'), ('SPC', 'SPORTS CAR'), ('STW', 'STATION WAGON'), ('HTB', 'HATCHBACK'), ('CVT', 'CONVERTIBLE'), ('SUV', 'SPORT-UTILITY VEHICLE'), ('MNV', 'MINIVAN'), ('PUT', 'PICKUP TRUCK')], default='SDN', max_length=3),
        ),
    ]
