# Generated by Django 3.1.4 on 2020-12-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20201223_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
