# Generated by Django 3.1.4 on 2020-12-23 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201223_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
